name: Setup Poetry
author: Alfi Maulana
description: Set up a specific version of Poetry
branding:
  color: black
  icon: terminal
inputs:
  version:
    description: The Poetry version to be set up.
    required: false
    default: latest
  cache:
    description: Use caching during Poetry installation.
    required: false
    default: true
runs:
  using: composite
  steps:
    - id: pipx
      if: inputs.cache == 'true'
      shell: bash
      run: |
        echo "version=$(pipx --version)" >> $GITHUB_OUTPUT
        echo "bin_dir=$(pipx environment -v PIPX_BIN_DIR)" >> $GITHUB_OUTPUT
        echo "local_venvs=$(pipx environment -v PIPX_LOCAL_VENVS)" >> $GITHUB_OUTPUT

    - id: cache
      if: inputs.cache == 'true'
      uses: actions/cache@v3.3.2
      with:
        path: |
          ${{ steps.pipx.outputs.bin_dir }}/poetry*
          ${{ steps.pipx.outputs.local_venvs }}/poetry
        key: pipx-${{ steps.pipx.outputs.version }}-${{ runner.os }}-poetry-${{ inputs.version }}

    - shell: bash
      if: inputs.cache != 'true' || steps.cache.outputs.cache-hit != 'true'
      run: |
        if [ '${{ inputs.version }}' == latest ]; then
          pipx install poetry --force
          pipx upgrade poetry --force
        else
          pipx install poetry==${{ inputs.version }} --force
        fi
