name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [Windows, Ubuntu, macOS]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          path: setup-poetry-action
          sparse-checkout: action.yaml

      - name: Poetry should not be available
        shell: bash
        run: "! which poetry"

      - name: Setup Poetry with caching
        uses: ./setup-poetry-action

      - name: Poetry should be available
        shell: bash
        run: which poetry

      - name: Poetry version should be correct
        shell: bash
        run: test "$(poetry --version)" == 'Poetry (version ${{ vars.POETRY_LATEST_VERSION }})'

      - name: Setup Poetry with a specific version
        uses: ./setup-poetry-action
        with:
          version: 1.5.1
          cache: false

      - name: Poetry version should be correct
        shell: bash
        run: test "$(poetry --version)" == 'Poetry (version 1.5.1)'

      - name: Setup Poetry
        uses: ./setup-poetry-action
        with:
          cache: false

      - name: Poetry version should be correct
        shell: bash
        run: test "$(poetry --version)" == 'Poetry (version ${{ vars.POETRY_LATEST_VERSION }})'
